express_kitchenapp-master/Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    
    path('account',include('accounts.urls')),
    path('stock/',include('stock.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),
    path('' , include('store.urls'))
]
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

express_kitchenapp-master/stock/urls.py
from django.urls import path
from .views import *
from stock import views




app_name='stock'
urlpatterns = [
   path('base', views.base, name='base'),
   path('add_items/', views.add_items, name='add_items'),
   path('list_item/', views.list_item, name='list_item'),
   path('update_items/<str:pk>/', views.update_items, name="update_items"),
   path('stock_detail/<str:pk>/', views.stock_detail, name="stock_detail"),
   path('issue_items/<str:pk>/', views.issue_items, name="issue_items"),
   path('receive_items/<str:pk>/', views.receive_items, name="receive_items"),
   path('reorder_level/<str:pk>/', views.reorder_level, name="reorder_level"),
   path('menu_items/<str:pk>/', views.menu_items, name="menu_items"),
   path('add_menu/', views.add_menu, name="add_menu"),
   path('menu/', views.menu, name='menu'),
   

]
 

express_kitchenapp-master/store/urls.py
from django.contrib import admin
from django.urls import path
from .views.home import Index , store
from .views.signup import Signup
from .views.login import Login , logout
from .views.cart import Cart
from .views.checkout import CheckOut
from .views.orders import OrderView, add_stock



app_name='store'

urlpatterns = [
    path('', Index.as_view(), name='homepage'),
    path('store/', store , name='store'),
    path('signup', Signup.as_view(), name='signup'),
    path('login', Login.as_view(), name='login'),
    path('logout', logout , name='logout'),
    path('cart/', Cart.as_view(), name='cart'),
    path('check-out', CheckOut.as_view() , name='checkout'),
    path('orders/', OrderView.as_view(), name='orders'),
    path('store_list/', OrderView.as_view(), name='store_list'),
    path('add_orders/', add_stock, name='add_stock'),
    # path('store_list/',store_list,name='store_list'),

]

express_kitchenapp-master/store/models/orders.py
from django.db import models
from .product import Product
from .customer import Customer
import datetime


class Order(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')

express_kitchenapp-master/stock/forms.py
from django import forms
from django.forms import fields
from django.forms.formsets import formset_factory
from .models import Menu, Stock
 

       
class StockCreateForm(forms.ModelForm):
    class Meta:
        model =Stock
        fields=['category','item_name','quantity',] # add fields in admin

    def clean_category(self):
        category = self.cleaned_data.get('category')
        if not category:
            raise forms.ValidationError('This field is required')
        return category


    def clean_item_name(self):
        item_name = self.cleaned_data.get('item_name')
        if not item_name:
            raise forms.ValidationError('This field is required')
        
        for instance in Stock.objects.all():
            if instance.item_name == item_name:
                raise forms.ValidationError(str(item_name) + ' is already created')
        return item_name



class StockSearchForm(forms.ModelForm):
    export_to_CSV = forms.BooleanField(required =False)
    class Meta:
        model = Stock
        fields = ['category', 'item_name']


class StockUpdateForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['category', 'item_name', 'quantity',]

class IssueForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['item_name','issue_quantity',]



class ReceiveForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['item_name','receive_quantity',]
        
class ReorderLevelForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['reorder_level']



class OrderCreateForm(forms.ModelForm):
    class Meta:
        model =Stock
        fields=['category','item_name','quantity',] 
        
        
class MenuForm(forms.ModelForm):
    class Meta:
        model =Menu
        fields=['item_name','quantity',] 

class AddMenu(forms.ModelForm):
    class Meta:
        model =Menu
        fields= ['item_name','issue_quantity'] # add fields in admin

    def clean_item_name(self):
        item_name = self.cleaned_data.get('item_name')
        if not item_name:
            raise forms.ValidationError('This field is required')
        
        for instance in Stock.objects.all():
            if instance.item_name == item_name:
                raise forms.ValidationError(str(item_name) + ' is already created')
        return item_name


 
       
       
class MenuSearchForm(forms.ModelForm):
    export_to_CSV = forms.BooleanField(required =False)
    class Meta:
        model = Menu
        fields = [ 'item_name']




# class AddMenu(forms.ModelForm):
#    class Meta:
#        model=Menu
#        fields= ['item_name','issue_quantity']

express_kitchenapp-master/stock/views.py
import csv
from django.http import request
from django.shortcuts import redirect, render
from .forms import *
from .models import *
from django.contrib import messages
from django.http import HttpResponse 
from django.contrib.auth.decorators import login_required


 
# Create your views here.

# @login_required
def base(request):
    title='Welcome:Stock management'
    form="welcome"
    context={
        "title":title,
        "test":form
       }
    return render (request,'base.html',context)

# @login_required
def list_item(request):
    header='Stock'
    form = StockSearchForm(request.POST or None)
    queryset = Stock.objects.all()
    context = {
        "header": header,
        "queryset": queryset,
        "form":form
    }
    
    if request.method == 'POST':
        queryset = Stock.objects.filter(
            # category__icontains=form['category'].value(),
            item_name__icontains=form['item_name'].value()
            )
     
        if form['export_to_CSV'].value() == True:
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="List of stock.csv"'
            writer = csv.writer(response)
            writer.writerow(['CATEGORY', 'ITEM NAME', 'QUANTITY'])
            instance = queryset
            for stock in instance:
                writer.writerow([stock.category, stock.item_name, stock.quantity])
            return response

        context = {
            "form": form,
            "header": 'header',
            "queryset": queryset,
                  }
    return render(request, "list_item.html", context)
# @login_required
def add_items(request):
    form=StockCreateForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Successfully Saved')
        return redirect('/stock/list_item')
    context={
        "form":form,
        "title":'Additems',
        }
    return render(request,"add_items.html",context)
    
# @login_required
def update_items(request, pk):
    queryset = Stock.objects.get(id=pk)
    form = StockUpdateForm(instance=queryset)
    if request.method == 'POST':
        form = StockUpdateForm(request.POST, instance=queryset)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully Saved')
            return redirect('/stock/list_item')
    context = {
        'form':form
	}
    return render(request, 'update_items.html', context)

# @login_required
def stock_detail(request, pk):
	queryset = Stock.objects.get(id=pk)
	context = {
		"queryset": queryset,
	}
	return render(request, "stock_detail.html", context)



# @login_required
def issue_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = IssueForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity -= instance.issue_quantity
		instance.issue_by = str(request.user)
		messages.success(request, "Issued SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name) + "s now left in Store")
		instance.save()

		return redirect('/stock/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": 'Issue ' + str(queryset.item_name),
		"queryset": queryset,
		"form": form,
		"username": 'Issue By: ' + str(request.user),
	}
	return render(request, "request.html", context)


# @login_required
def receive_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = ReceiveForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity += instance.receive_quantity
		instance.save()
		messages.success(request, "Received SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name)+"s now in Store")

		return redirect('/stock/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": 'Receive ' + str(queryset.item_name),
			"instance": queryset,
			"form": form,
			"username": 'Receive By: ' + str(request.user),
		}
	return render(request, "receive.html", context)

# @login_required
def reorder_level(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = ReorderLevelForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Reorder level for " + str(instance.item_name) + " is updated to " + str(instance.reorder_level))

		return redirect("/stock/list_item")
	context = {
			"instance": queryset,
			"form": form,
		}
	return render(request, "add_items.html", context)

    
# Requesting for menu
# @login_required
def menu_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = IssueForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity -= instance.issue_quantity
		instance.issue_by = str(request.user)
		messages.success(request, "Issued SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name) + "s now left in Store")
		instance.save()

		return redirect('/stock/stock_detail/'+str(instance.id))
		

	context = {
		"title": 'Issue ' + str(queryset.item_name),
		"queryset": queryset,
		"form": form,
		"username": 'Issue By: ' + str(request.user),
	}
	return render(request, "request.html", context)


# # ADD MENU
# @login_required
def add_menu(request):
    form=AddMenu(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Successfully Saved')
        return redirect('/stock/menu')
    context={
        "form":form,
        "title":'Additems',
        }
    return render(request,"add_menu.html",context)




# @login_required
def menu(request):
    header='Menu'
    form = MenuSearchForm(request.POST or None)
    queryset = Menu.objects.all()
    context = {
        "header": header,
        "queryset": queryset,
        "form":form
    }
    
    if request.method == 'POST':
        queryset = Menu.objects.filter(
            # category__icontains=form['category'].value(),
            item_name__icontains=form['item_name'].value()
            )
     
        if form['export_to_CSV'].value() == True:
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="List of Menu.csv"'
            writer = csv.writer(response)
            writer.writerow(['CATEGORY', 'ITEM NAME', 'QUANTITY'])
            instance = queryset
            for menu in instance:
                writer.writerow([menu.category, menu.item_name, menu.quantity])
            return response

        context = {
            "form": form,
            "header": 'header',
            "queryset": queryset,
                  }
    return render(request, "menu.html", context)



# @login_required
def update_menu(request, pk):
    queryset = Stock.objects.get(id=pk)
    form = StockUpdateForm(instance=queryset)
    if request.method == 'POST':
        form = StockUpdateForm(request.POST, instance=queryset)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully Saved')
            return redirect('/stock/menu')
    context = {
        'form':form
	}
    return render(request, 'add_menu.html', context)

express_kitchenapp-master/store/views/orders.py
import csv
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from store.forms import StoreCreateForm, StoreSearchForm
from django.views import View
from store.models.orders import Order
from store.models.product import Product

class OrderView(View):
    def get(self,request):
        orders = Order.objects.all()
        print(orders)
        return render(request , 'orders.html'  , {'orders' : orders})


    # def get(self , request ):
    #     customer = request.session.get('customer')
    #     orders = Order.get_orders_by_customer(customer)
    #     print(orders)
    #     return render(request , 'orders.html'  , {'orders' : orders})

    def store_list(self , request ):
        customer = request.session.get('customer')
        order = Order.get_orders_by_customer(customer)
        print(order)
        return render(request , 'store.html'  , {'order' : order})
    
def add_stock(request):
    form=StoreCreateForm(request.POST,request.FILES)
    if form.is_valid():
        form.save()
        messages.success(request, 'Successfully Saved')
        return redirect('/store')
    context={
        "form":form,
        "title":'Additems',
        }
    return render(request,"add_stock.html",context)

# def store_list(request):
#     header='Store'
#     form = StoreCreateForm(request.POST or None)
#     queryset = Product.objects.all()
#     context = {
#         "header": header,
#         "queryset": queryset,
#         "form":form
#     }
    
#     if request.method == 'POST':
#         queryset = Product.objects.filter(
#             item_name__icontains=form['name'].value()
#             )
     
#         if form['export_to_CSV'].value() == True:
#             response = HttpResponse(content_type='text/csv')
#             response['Content-Disposition'] = 'attachment; filename="List of stock.csv"'
#             writer = csv.writer(response)
#             writer.writerow(['CATEGORY', 'NAME', 'QUANTITY'])
#             instance = queryset
#             for product in instance:
#                 writer.writerow([product.category, product.name, product.quantity])
#             return response

#         context = {
#             "form": form,
#             "header": 'header',
#             "queryset": queryset,
#                   }
#     return render(request,"store.html", context)
# @login_required

express_kitchenapp-master/stock/templates/add_items.html
{% include 'navbar.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link  href= " {% static 'css/style.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <div class="form">
     <form method="POST" enctype="multipart/form-data">
         {%csrf_token%}
        <h1>Add stock</h1>
         {{form.as_p}}
        <center> <button class="mybtn">Submit</button></center>
     </form>
     </div>
     </div>
   
    <style>
  
        h1{
            text-align: center;
        }
          body{
              background-color:white;
              align-items: center;
              justify-content: center;
              font-size: 20px;
              color:purple;
          }
          input{
             width: 100%;
             outline: none;
             border: 1px solid ;
             font-size: 15px;
             padding: 8px 8px;
             border-radius: 20px;
         }
         select{
             width: 100%;
             padding: 8px 10px;
             border-radius: 3px;
             transition: all 0.3;
         }
         .wrapper{
        max-width: 500px;
        width: 80%;
        background: #fff;
        margin: 20px auto;
        padding: 50px;
        box-shadow: 1px 1px 2px rgba(0,0,0, 125);
        padding-left: 25%;
         }
         .wrapper.form.inputfield{
             margin-bottom: 15px;
             display: flex;
             align-items: center;
         }
         .wrapper.wrapper.form.input_field label{
             width: 200px;
             color: black;
             margin-right: 10px;
             font-size: 14px;
         }
        button{
            top: 30px;
            height: 50px;
            width :12%;
            border-radius: 6px;
            align-items: center;
            font-size: 1rem;
            background-color: rgb(226, 191, 226);
            
        }
        .pic{
            background-size: contain;
            width: 80%;
            text-align: center;
            height: 150px;
        }
        button:hover{
            color: white;
            background-color: purple;
            cursor: pointer;
        }
       .mybtn{
        top: 30px;
        height: 50px;
        width :40%;
        border-radius: 6px;
        align-items: center;
        font-size: 1.4rem;
        background-color: rgb(226, 191, 226);
       }
       .mybtn:hover{
        color: white;
        background-color: purple;
        cursor: pointer;
           
       }
        
  
    </style>
</body>
</html>

express_kitchenapp-master/stock/templates/list_item.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List item</title>
</head>

<body>
    
    {% if messages %}
    <ul class="messages">
           {% for message in messages %}
                 <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
           {% endfor %}
   </ul>
{% endif %}

    <div class="header" {{header}}>stock</div>
    
<div class="search">

    <form method='POST' action=''>{% csrf_token %}
        {{form}}
            <input type="submit" value='Search'/>
    </form>
    <br>
</div>



    <div class="display_table">
        <table class='table'>
           
                <tr>
                    <th>COUNT</th>
                    <th>CATEGORY</th>
                    <th>ITEM NAME</th>
                    <th>QUANTITY IN STORE</th>
                    <th>REORDER LEVEL</th>
                    <th>TIMESTAMP</th>
                    <th>LAST UPDATED</th>
                  
                   
                </tr>
        

            {% for instance in queryset %}
            <tr>

                <td>{{forloop.counter}}</td>
                <td>{{instance.category}}</td>
                <td><a href="{% url 'stock:update_items' instance.id %}" >{{instance.item_name}}</a></td>
                
                    <!-- {% if instance.quantity <= instance.reorder_level %}
                    <div style="background-color: red;">
                     <a href="{% url 'stock:stock_detail' instance.id %}" >{{instance.quantity}}</a>
                    <a href="{% url 'stock:stock_detail' instance.id %}" ></a>{{instance.quantity}}
                    </div>
                    {% else %}
                    <a href="{% url 'stock:stock_detail' instance.id %}" ></a>{{instance.reorder_level}}
                    {% endif %} -->
                  
                <td> <a href="{% url 'stock:stock_detail' instance.id %}" >{{instance.quantity}}</a></td> 
                <td><a href="{% url 'stock:reorder_level' instance.id %}">{{instance.reorder_level}}</a></td>
                <td>{{instance.timestamp}}</td>
                <td>{{instance.last_updated}}</td>


               
            </tr>
            {% endfor %}
        </table>
    </div>

    
<style>
    .header{
        text-align: center;
        text-shadow: 6px 6px 6px #c9c6c6;

        font-family: helvetica;
        color: purple;
        font-size: 50px;
        text-align: center;
        width: 100%;
        text-shadow: 6px 6px 6px #c9c6c6;
        display: block;
        font-weight: bolder;
        padding: 2%;
    }
    .stock{
       margin-left: 190px;
       background-color:rgb(244, 240, 245);
  
    }
    .table {
        font-size: 13px;
        text-align: center;
        width: 95%;
        margin: auto;
        text-align: center;
        border-collapse: collapse;
        border: 1px solid black;
    }
        
    .display_table {

        padding-left: 210px;
        padding-right: 40px;
        padding-bottom: 20px;
        box-shadow: 12px 12px 20px 6px rgb(189, 163, 189);
    }
     table, td, th {
       border: 1px solid #ddd;
       text-align: left;
       border: 1px solid black;
       margin-left: 20px;
       font-size: 12px;
      

    
     }
     tr:hover {
       background-color:rgb(244, 240, 245);
       cursor: pointer;
     }
     th, td {
       padding: 15px;
     }
     th{
       background-color: rgb(221, 168, 226);
       color: black;
     }
     .success{
        list-style: none;
        background-color: #2e6da4;
        color: white;
        box-shadow: 12px 12px 12px rgb(221, 168, 226);;
        text-align: center;
    }
    .search{
        padding-left: 30%;
    }
</style>
    
</body>

</html>

express_kitchenapp-master/stock/templates/menu.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List item</title>
</head>

<body>
    
    {% if messages %}
    <ul class="messages">
           {% for message in messages %}
                 <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
           {% endfor %}
   </ul>
{% endif %}

    <div class="header" {{header}}>Menu</div>
    
<div class="search">

    <form method='POST' action=''>{% csrf_token %}
        {{form}}
            <input type="submit" value='Search'/>
    </form>
    <br>
</div>



    <div class="display_table">
        <table class='table'>
           
                <tr>
                   
                 
                    <th>ITEM NAME</th>
                    <th>QUANTITY</th>
                   
                </tr>
        

            {% for instance in queryset %}
            <tr>  
 
                <td><a href="{% url 'stock:issue_items' instance.id %}" >{{instance.item_name}}</a></td>                <!-- <td>{{instance.item_name}}</td> -->
               <td>{{instance.issue_quantity}}</td>
       
            </tr>

          
            {% endfor %}

          
        </table>
        <center> <button>request</button></center>
        
    </div>

    
<style>
    .header{
        text-align: center;
        text-shadow: 6px 6px 6px #c9c6c6;

        font-family: helvetica;
        color: purple;
        font-size: 50px;
        text-align: center;
        width: 100%;
        text-shadow: 6px 6px 6px #c9c6c6;
        display: block;
        font-weight: bolder;
        padding: 2%;
    }
    .stock{
       margin-left: 190px;
       background-color:rgb(244, 240, 245);
  
    }
    .table {
        font-size: 13px;
        text-align: center;
        width: 95%;
        margin: auto;
        text-align: center;
        border-collapse: collapse;
        border: 1px solid black;
    }
        
    .display_table {

        padding-left: 210px;
        padding-right: 40px;
        padding-bottom: 20px;
        box-shadow: 12px 12px 20px 6px rgb(189, 163, 189);
    }
     table, td, th {
       border: 1px solid #ddd;
       text-align: left;
       padding-right: 48px;
       border: 1px solid black;
      

    
     }
     tr:hover {
       background-color:rgb(244, 240, 245);
       cursor: pointer;
     }
     th, td {
       padding: 15px;
     }
     th{
       background-color: rgb(221, 168, 226);
  
     
       color: black;
     }
     .success{
        list-style: none;
        background-color: #2e6da4;
        color: white;
        box-shadow: 12px 12px 12px rgb(221, 168, 226);;
        text-align: center;
    }
    .search{
        padding-left: 30%;
    }

    button{
        top: 30px;
        height: 50px;
        width :12%;
        border-radius: 6px;
        align-items: center;
        font-size: 1rem;
        background-color: rgb(226, 191, 226);
        margin: 2%;
        
    }
</style>
    
</body>

</html>

express_kitchenapp-master/stock/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <a href="/accounts/logout"><button class="btn btn-danger">{{ user }} | Logout</button></a></li>
        {% else %}
        <a href="/accounts/login">Login</a>
        {% endif %}
    </ul>

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
</head>
<body>
    <ul class="mytop-nav">
        <li class=" nav-li"><a href="{% url 'store:store_list' %}">Stock</a></li>
        <li class=" nav-li"><a href="{% url 'store:add_stock' %}">Add stock</a></li> 
        <li class=" nav-li"><a href="{% url 'stock:menu' %}">Menu</a></li>
        <li class=" nav-li"><a href="{% url 'stock:add_menu' %}">Add menu </a></li>
        <li class=" nav-li"><a href="{% url 'store:store' %}">Order</a></li>
->

     </ul>
     <style>

    .mytop-nav{
        letter-spacing: none;
        margin: -8px;
        padding-left: 20px;
        width: 150px;
        height: 100%;
        background-color:#812990;
        position: fixed;
        list-style: none;
        margin-top: -55px;
        box-shadow: 5px 5px 8px 1px rgb(189, 163, 189);
           }

   .nav-li a{
        display: block;
        width: 150px;
        color:white;
        text-decoration: none;
        font-size: 20px;
        padding-bottom: -20px;
        margin-bottom: 20px;
        margin-top: 40px;
        padding: 12px 16px;
        
        
    }
    .nav-li a:hover{
        background-color: white;
        color:black;
        height: 12px;
        width: 80%;
       
    } 
    .heading{
        margin-left: 400px;
        font-size: 70px;
        padding-top: 85px;
    }
    .navbar-nav{
        padding-left:75%;
        height: 30px;
        width: 95%;
        margin-top: 0%;

        

    }
</style>

</body>
</html>

</body>
</html>

express_kitchenapp-master/stock/templates/stock_detail.html
{% include 'navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class=" padd"> 
<a href="{% url 'stock:issue_items' queryset.id %}"><div class='btn-issue'><button>REQUEST THIS ITEM</button> </div></a>

<a href="{% url 'stock:receive_items' queryset.id %}"><div class='btn-receive'><button> RECEIVE THIS ITEM</button></div></a>


        <div class="display_table">
          <table class='table'>
                  <tr>
                    <th>ITEM NAME</th>
                    <th>QUANTITY IN STORE</th>
                    <th>REORDER LEVEL</th>
                    
                    
                  </tr>
                  <tr>
                    <td>{{queryset.item_name}}</td>
                    <td>{{queryset.quantity}}</a></td>
                    <td>{{queryset.reorder_level}}</td>
                   
                    
                  </tr>
          </table>
        </div>

    </div> 
        <style>
            .header {
                font-family: helvetica;
                color: purple;
                font-size: 50px;
                text-align: center;
                width: 100%;
                text-shadow: 6px 6px 6px #c9c6c6;
                display: block;
                font-weight: bolder;
                padding: 2%;
            }
    
            /*Align the title to the center of the page*/
            .table {
                font-size: 13px;
                text-align: center;
                width: 95%;
                margin: auto;
                text-align: center;
                border-collapse: collapse;
                border: 1px solid black;
            }
    
            table, th, td {
                border: 1px solid black;
              }
            /*Make alternating colors for the table rows*/
            .table tr:nth-child(odd) {
                background: rgb(122, 14, 122);
                color: white;
    
            }
    
            .table tr:nth-child(even) {
                background: white;
            }
    
            th {
                background-color: rgb(122, 14, 122);
                color: white;
                padding: 2%;
    
            }
    
            td {
                padding: 2%;
            }
    
            .display_table {

                padding-left:15%;
                padding-right: 5px;
                padding-bottom: 20px;
                box-shadow: 12px 12px 20px 6px rgb(189, 163, 189);
            }
            .success{
                list-style: none;
                background-color: plum;
                color: white;
                box-shadow: 12px 12px 12px plum;
                text-align: center;
            }
            button{
                
                height:50px;
                width :20%;
                border-radius: 6px;
                align-items: center;
                font-size: 1rem;
                background-color: rgb(226, 191, 226);
                
            }
           .btn-receive{
               padding-left: 50%;
               margin-top: -8%;
               height: auto;
               width: 100%;
               padding-bottom: 80px;
               

           }
           .btn-issue{
            padding-left: 25%;
            height: auto;
            margin-top: 1px;
            width: 100%;
            padding-bottom: 40px;
        
           }
           .padd{
               margin-bottom: 80%;
           }
        </style>
    
</body>
</html>